<a href="https://colab.research.google.com/github/chingyaousf/Machine-Learning-Prediction-of-NGFK-dependency-in-HNC-Head-and-Neck-Cancer-/blob/main/scripts/MLpredictionDep_01_data_construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read the CSV file
arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/arranged_table.csv")

# Transpose the DataFrame
arranged_table_transposed = arranged_table.transpose()

# Reset the index and set new column names
arranged_table_transposed = arranged_table_transposed.reset_index()
arranged_table_transposed.columns = arranged_table_transposed.iloc[0]
arranged_table_transposed = arranged_table_transposed.iloc[1:]

# Adjust the leftmost column to count from 0
arranged_table_transposed.reset_index(drop=True, inplace=True)

# Save the transposed DataFrame to a CSV file
arranged_table_transposed.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/arranged_table_transposed.csv", index=False)

arranged_table_transposed

,DepMap_ID,A1BG (1) Dep,A1BG (1) Exp,A1CF (29974) Dep,A1CF (29974) Exp,A2M (2) Dep,A2M (2) Exp,A2ML1 (144568) Dep,A2ML1 (144568) Exp,A3GALT2 (127550) Dep,...,ZYG11A (440590) Dep,ZYG11A (440590) Exp,ZYG11B (79699) Dep,ZYG11B (79699) Exp,ZYX (7791) Dep,ZYX (7791) Exp,ZZEF1 (23140) Dep,ZZEF1 (23140) Exp,ZZZ3 (26009) Dep,ZZZ3 (26009) Exp
0,ACH-000001,0.094568,3.116032,0.012519,0.056584,0.02746,0.226509,0.025962,0.111031,0.073412,...,0.082956,3.28244,0.012,2.797013,0.003592,6.821455,0.012679,3.01078,0.324623,4.381975
1,ACH-000004,0.012676,4.178715,0.049011,0.0,0.075933,0.214125,0.033215,0.344828,0.013176,...,0.060266,0.014355,0.128375,2.032101,0.005911,7.002252,0.004645,3.444932,0.04253,4.910733
2,ACH-000005,0.053957,4.003602,0.027968,0.014355,0.010139,0.137504,0.005448,0.014355,0.018599,...,0.034712,0.014355,0.092832,2.761285,0.012482,6.826421,0.020843,3.524816,0.050412,5.592457
3,ACH-000007,0.026704,0.137504,0.083588,1.405992,0.008853,0.201634,0.011299,0.0,0.027288,...,0.035241,0.014355,0.138445,1.989139,0.103161,6.332708,0.146222,3.673556,0.274833,3.469886
4,ACH-000009,0.059383,1.464668,0.051826,3.586164,0.01537,0.250962,0.011721,0.0,0.030062,...,0.18955,1.356144,0.328064,2.956057,0.035161,7.853185,0.058402,3.44228,0.269194,3.351911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,0.063758,1.967169,0.039244,0.0,0.029825,2.198494,0.034174,0.0,0.139199,...,0.068998,0.014355,0.144264,4.173127,0.067693,6.560256,0.081846,2.969012,0.131433,5.276869
1001,ACH-002800,0.030591,3.847997,0.040334,0.0,0.00188,5.899901,0.005053,0.321928,0.154874,...,0.040005,0.62293,0.077345,3.084064,0.038227,6.596935,0.048967,3.177918,0.033994,4.847997
1002,ACH-002834,0.01272,1.819668,0.08384,0.014355,0.013308,0.014355,0.013315,0.201634,0.107286,...,0.029711,1.400538,0.024132,2.568032,0.174946,6.953498,0.09151,3.087463,0.421153,4.226509
1003,ACH-002847,0.058547,2.990955,0.079576,0.0,0.036707,7.60844,0.030234,0.014355,0.069976,...,0.072452,1.480265,0.131375,2.748461,0.115486,7.432041,0.094022,2.903038,0.438092,4.660495
1004,ACH-002926,0.02201,3.189034,0.023496,0.0,0.012432,9.33539,0.00742,0.014355,0.018041,...,0.028312,0.014355,0.104833,2.776104,0.008261,5.182295,0.035919,2.956057,0.404214,3.785551

In [1]:
import pandas as pd

# Read the CSV file
arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/arranged_table_transposed.csv")

# Separate the column names with "Exp" and "Dep"
exp_columns = [col for col in arranged_table.columns if col.endswith(" Exp")]
dep_columns = [col for col in arranged_table.columns if col.endswith(" Dep")]

# Reorder the columns with "Exp" on the left and "Dep" on the right
new_columns = ["DepMap_ID"] + exp_columns + dep_columns

# Create a new DataFrame with the reordered columns
arranged_table_reordered = arranged_table[new_columns]

# Adjust the leftmost column to count from 0
arranged_table_reordered.reset_index(drop=True, inplace=True)

arranged_table_reordered

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,...,ZWILCH (55055) Dep,ZWINT (11130) Dep,ZXDA (7789) Dep,ZXDB (158586) Dep,ZXDC (79364) Dep,ZYG11A (440590) Dep,ZYG11B (79699) Dep,ZYX (7791) Dep,ZZEF1 (23140) Dep,ZZZ3 (26009) Dep
0,ACH-000001,3.116032,0.056584,0.226509,0.111031,0.000000,1.035624,0.176323,5.700440,4.144046,...,0.037449,0.080585,0.034309,0.007142,0.004241,0.082956,0.012000,0.003592,0.012679,0.324623
1,ACH-000004,4.178715,0.000000,0.214125,0.344828,0.070389,0.097611,0.000000,6.336819,3.231125,...,0.038768,0.230569,0.007125,0.021209,0.011203,0.060266,0.128375,0.005911,0.004645,0.042530
2,ACH-000005,4.003602,0.014355,0.137504,0.014355,0.000000,0.028569,0.000000,6.337176,3.781360,...,0.017479,0.274568,0.054525,0.033396,0.033416,0.034712,0.092832,0.012482,0.020843,0.050412
3,ACH-000007,0.137504,1.405992,0.201634,0.000000,0.000000,0.014355,0.000000,5.431289,4.300856,...,0.196233,0.615338,0.011212,0.002200,0.005432,0.035241,0.138445,0.103161,0.146222,0.274833
4,ACH-000009,1.464668,3.586164,0.250962,0.000000,0.042644,4.525443,0.000000,5.674122,4.510962,...,0.152385,0.405712,0.029011,0.002816,0.056461,0.189550,0.328064,0.035161,0.058402,0.269194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,1.967169,0.000000,2.198494,0.000000,0.000000,1.490570,0.000000,5.300490,4.314697,...,0.097896,0.126051,0.014528,0.009290,0.045986,0.068998,0.144264,0.067693,0.081846,0.131433
1001,ACH-002800,3.847997,0.000000,5.899901,0.321928,0.000000,3.206331,0.000000,5.831877,3.822730,...,0.004340,0.195897,0.029177,0.002176,0.014489,0.040005,0.077345,0.038227,0.048967,0.033994
1002,ACH-002834,1.819668,0.014355,0.014355,0.201634,0.000000,2.912650,0.028569,5.646451,4.547820,...,0.027170,0.636352,0.022403,0.052849,0.029567,0.029711,0.024132,0.174946,0.091510,0.421153
1003,ACH-002847,2.990955,0.000000,7.608440,0.014355,0.000000,0.584963,0.000000,5.104337,4.228819,...,0.476423,0.967625,0.014249,0.018715,0.010776,0.072452,0.131375,0.115486,0.094022,0.438092
1004,ACH-002926,3.189034,0.000000,9.335390,0.014355,0.000000,0.000000,0.014355,5.204376,4.405992,...,0.669718,0.939699,0.013556,0.001120,0.057491,0.028312,0.104833,0.008261,0.035919,0.404214

In [ ]:
# Find the column names containing the specified strings
target_columns = arranged_table_reordered.columns[arranged_table_reordered.columns.str.contains('EIF2AK3|SF3B1|NQO1|SQSTM1|MYC|HSP70')]

target_columns

Index(['EIF2AK3 (9451) Exp', 'MYC (4609) Exp', 'MYCBP (26292) Exp',
       'MYCBPAP (84073) Exp', 'MYCL (4610) Exp', 'MYCN (4613) Exp',
       'MYCT1 (80177) Exp', 'NQO1 (1728) Exp', 'SF3B1 (23451) Exp',
       'SQSTM1 (8878) Exp', 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep',
       'MYCBP (26292) Dep', 'MYCBPAP (84073) Dep', 'MYCL (4610) Dep',
       'MYCN (4613) Dep', 'MYCT1 (80177) Dep', 'NQO1 (1728) Dep',
       'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep'],
      dtype='object')

In [ ]:
# Find the column names exactly matching the specified strings
target_columns = arranged_table_reordered.columns[arranged_table_reordered.columns.str.match('EIF2AK3 |SF3B1 |NQO1 |SQSTM1 |MYC |HSP70 ')]

target_columns

Index(['EIF2AK3 (9451) Exp', 'MYC (4609) Exp', 'NQO1 (1728) Exp',
       'SF3B1 (23451) Exp', 'SQSTM1 (8878) Exp', 'EIF2AK3 (9451) Dep',
       'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep',
       'SQSTM1 (8878) Dep'],
      dtype='object')

In [ ]:
# Create a list of column names to preserve

preserved_columns = ["EIF2AK3", "SF3B1", "NQO1", "SQSTM1", "MYC", "HSP70"]

# Filter the columns based on the preserved column names
filtered_columns = [col for col in arranged_table_reordered.columns if (col.endswith(" Dep") and col.split(" ")[0] in preserved_columns) or not col.endswith(" Dep")]

# Create a new DataFrame with the filtered columns
filtered_arranged_table = arranged_table_reordered[filtered_columns]

# Save the filtered_arranged_table DataFrame to a CSV file
filtered_arranged_table.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv", index=False)

filtered_arranged_table

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,...,ZYG11A (440590) Exp,ZYG11B (79699) Exp,ZYX (7791) Exp,ZZEF1 (23140) Exp,ZZZ3 (26009) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,3.116032,0.056584,0.226509,0.111031,0.000000,1.035624,0.176323,5.700440,4.144046,...,3.282440,2.797013,6.821455,3.010780,4.381975,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,4.178715,0.000000,0.214125,0.344828,0.070389,0.097611,0.000000,6.336819,3.231125,...,0.014355,2.032101,7.002252,3.444932,4.910733,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,4.003602,0.014355,0.137504,0.014355,0.000000,0.028569,0.000000,6.337176,3.781360,...,0.014355,2.761285,6.826421,3.524816,5.592457,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,0.137504,1.405992,0.201634,0.000000,0.000000,0.014355,0.000000,5.431289,4.300856,...,0.014355,1.989139,6.332708,3.673556,3.469886,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,1.464668,3.586164,0.250962,0.000000,0.042644,4.525443,0.000000,5.674122,4.510962,...,1.356144,2.956057,7.853185,3.442280,3.351911,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,1.967169,0.000000,2.198494,0.000000,0.000000,1.490570,0.000000,5.300490,4.314697,...,0.014355,4.173127,6.560256,2.969012,5.276869,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,3.847997,0.000000,5.899901,0.321928,0.000000,3.206331,0.000000,5.831877,3.822730,...,0.622930,3.084064,6.596935,3.177918,4.847997,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,1.819668,0.014355,0.014355,0.201634,0.000000,2.912650,0.028569,5.646451,4.547820,...,1.400538,2.568032,6.953498,3.087463,4.226509,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,2.990955,0.000000,7.608440,0.014355,0.000000,0.584963,0.000000,5.104337,4.228819,...,1.480265,2.748461,7.432041,2.903038,4.660495,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.189034,0.000000,9.335390,0.014355,0.000000,0.000000,0.014355,5.204376,4.405992,...,0.014355,2.776104,5.182295,2.956057,3.785551,0.017135,0.963046,0.022057,0.998453,0.055990

In [2]:
# Create filtered_arranged_hnc_table.csv
# Create a list of column names to preserve

preserved_columns = ['AKT1', 'EGFR', 'NOTCH3', 'AKT3', 'NOTCH2', 'MAPK3', 'MET', 'AKT2', 'MAPK1', 'NOTCH1']

# Filter the columns based on the preserved column names
filtered_columns = [col for col in arranged_table_reordered.columns if (col.endswith(" Dep") and col.split(" ")[0] in preserved_columns) or not col.endswith(" Dep")]

# Create a new DataFrame with the filtered columns
filtered_arranged_hnc_table = arranged_table_reordered[filtered_columns]

# Save the filtered_arranged_table DataFrame to a CSV file
filtered_arranged_hnc_table.to_csv("/content/drive/MyDrive/Colab Notebooks/features engineering/filtered_arranged_hnc_table.csv", index=False)

filtered_arranged_hnc_table

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,...,AKT1 (207) Dep,AKT2 (208) Dep,AKT3 (10000) Dep,EGFR (1956) Dep,MAPK1 (5594) Dep,MAPK3 (5595) Dep,MET (4233) Dep,NOTCH1 (4851) Dep,NOTCH2 (4853) Dep,NOTCH3 (4854) Dep
0,ACH-000001,3.116032,0.056584,0.226509,0.111031,0.000000,1.035624,0.176323,5.700440,4.144046,...,0.010809,0.047841,0.011180,0.058504,0.015144,0.130345,0.035369,0.080012,0.012757,0.029946
1,ACH-000004,4.178715,0.000000,0.214125,0.344828,0.070389,0.097611,0.000000,6.336819,3.231125,...,0.017735,0.014966,0.005170,0.026705,0.030264,0.115061,0.043774,0.034722,0.037272,0.059803
2,ACH-000005,4.003602,0.014355,0.137504,0.014355,0.000000,0.028569,0.000000,6.337176,3.781360,...,0.076083,0.089749,0.000301,0.053187,0.036138,0.041554,0.045365,0.144591,0.144999,0.023495
3,ACH-000007,0.137504,1.405992,0.201634,0.000000,0.000000,0.014355,0.000000,5.431289,4.300856,...,0.060026,0.018062,0.009606,0.772103,0.071000,0.047310,0.054315,0.085632,0.030331,0.012053
4,ACH-000009,1.464668,3.586164,0.250962,0.000000,0.042644,4.525443,0.000000,5.674122,4.510962,...,0.027071,0.036544,0.058257,0.960308,0.354088,0.031446,0.080074,0.062992,0.072876,0.032109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,1.967169,0.000000,2.198494,0.000000,0.000000,1.490570,0.000000,5.300490,4.314697,...,0.077891,0.035609,0.013046,0.071244,0.036858,0.153179,0.106557,0.022251,0.017128,0.023691
1001,ACH-002800,3.847997,0.000000,5.899901,0.321928,0.000000,3.206331,0.000000,5.831877,3.822730,...,0.064771,0.023082,0.000226,0.049159,0.404692,0.010889,0.436147,0.028846,0.002251,0.030036
1002,ACH-002834,1.819668,0.014355,0.014355,0.201634,0.000000,2.912650,0.028569,5.646451,4.547820,...,0.072872,0.150488,0.016647,0.143674,0.595750,0.109431,0.054756,0.027227,0.061015,0.019873
1003,ACH-002847,2.990955,0.000000,7.608440,0.014355,0.000000,0.584963,0.000000,5.104337,4.228819,...,0.041685,0.079168,0.029636,0.610254,0.087387,0.050901,0.085068,0.034314,0.016053,0.036186
1004,ACH-002926,3.189034,0.000000,9.335390,0.014355,0.000000,0.000000,0.014355,5.204376,4.405992,...,0.009673,0.030929,0.002899,0.098730,0.137898,0.031720,0.063296,0.024660,0.030163,0.022431

In [ ]:
# Display Oral_Squamous_Cell_Carcinoma CCL (Cancer Cell Line)

import pandas as pd

# Read the CSV file
Oral_Squamous_Cell_Carcinoma = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/Oral_Squamous_Cell_Carcinoma.csv")

Oral_Squamous_Cell_Carcinoma

,ModelID,PatientID,CellLineName,StrippedCellLineName,OncotreeSubtype
0,ACH-000181,PT-UbMDmb,SCC-9,SCC9,Oral Cavity Squamous Cell Carcinoma
1,ACH-000188,PT-Iz4kXj,SCC-25,SCC25,Oral Cavity Squamous Cell Carcinoma
2,ACH-000228,PT-HX0QLG,BICR 31,BICR31,Oral Cavity Squamous Cell Carcinoma
3,ACH-000238,PT-Kf5TA3,SCC-4,SCC4,Oral Cavity Squamous Cell Carcinoma
4,ACH-000254,PT-nowpOK,SCC-15,SCC15,Oral Cavity Squamous Cell Carcinoma
5,ACH-000472,PT-MxVfNi,HSC-2,HSC2,Oral Cavity Squamous Cell Carcinoma
6,ACH-000503,PT-9uZV0s,BICR 16,BICR16,Oral Cavity Squamous Cell Carcinoma
7,ACH-000518,PT-czsVU5,CAL-33,CAL33,Oral Cavity Squamous Cell Carcinoma
8,ACH-000546,PT-F3GXIi,HSC-4,HSC4,Oral Cavity Squamous Cell Carcinoma
9,ACH-000548,PT-p0K5QM,BHY,BHY,Oral Cavity Squamous Cell Carcinoma
10,ACH-000606,PT-qno39F,PE/CA-PJ34 (clone C12),PECAPJ34CLONEC12,Oral Cavity Squamous Cell Carcinoma
11,ACH-000619,PT-UF0NQM,PE/CA-PJ15,PECAPJ15,Oral Cavity Squamous Cell Carcinoma
12,ACH-000630,PT-uty9xg,YD-8,YD8,Oral Cavity Squamous Cell Carcinoma
13,ACH-000723,PT-eFL4J2,YD-10B,YD10B,Oral Cavity Squamous Cell Carcinoma
14,ACH-000732,PT-mK3rFG,PE/CA-PJ41 (clone D2),PECAPJ41CLONED2,Oral Cavity Squamous Cell Carcinoma
15,ACH-000735,PT-M3R2ei,PE/CA-PJ49,PECAPJ49,Oral Cavity Squamous Cell Carcinoma
16,ACH-000740,PT-T4PL7e,A-253,A253,Oral Cavity Squamous Cell Carcinoma
17,ACH-000771,PT-59aO2P,BICR 56,BICR56,Oral Cavity Squamous Cell Carcinoma
18,ACH-000778,PT-XJviYz,HSC-3,HSC3,Oral Cavity Squamous Cell Carcinoma
19,ACH-000794,PT-zkbKhd,BICR 22,BICR22,Oral Cavity Squamous Cell Carcinoma
20,ACH-000832,PT-JCJHPr,CAL 27,CAL27,Oral Cavity Squamous Cell Carcinoma
21,ACH-000836,PT-ZS5SNw,YD-15,YD15,Oral Cavity Squamous Cell Carcinoma
22,ACH-001090,PT-yu1MA4,HN,HN,Oral Cavity Squamous Cell Carcinoma
23,ACH-001227,PT-k3C7C0,UPCI-SCC-090,UPCISCC090,Oral Cavity Squamous Cell Carcinoma
24,ACH-001228,PT-k3C7C0,UPCI-SCC-152,UPCISCC152,Oral Cavity Squamous Cell Carcinoma
25,ACH-001229,PT-FRJzoR,UPCI-SCC-154,UPCISCC154,Oral Cavity Squamous Cell Carcinoma
26,ACH-001331,PT-oQXmqM,BICR 10,BICR10,Oral Cavity Squamous Cell Carcinoma
27,ACH-001332,PT-aRE4u7,BICR 78,BICR78,Oral Cavity Squamous Cell Carcinoma
28,ACH-001346,PT-VXDXrs,H103,H103,Oral Cavity Squamous Cell Carcinoma
29,ACH-001347,PT-C880aD,H157,H157,Oral Cavity Squamous Cell Carcinoma
30,ACH-001509,PT-jrbPZG,H357,H357,Oral Cavity Squamous Cell Carcinoma
31,ACH-001510,PT-8wgZXD,H376,H376,Oral Cavity Squamous Cell Carcinoma
32,ACH-001511,PT-L1Obji,H413,H413,Oral Cavity Squamous Cell Carcinoma
33,ACH-001542,PT-wu5c1x,KON,KON,Oral Cavity Squamous Cell Carcinoma
34,ACH-001543,PT-1EAB3W,KOSC-2,KOSC2,Oral Cavity Squamous Cell Carcinoma
35,ACH-001625,PT-FeUEcM,OSC-19,OSC19,Oral Cavity Squamous Cell Carcinoma
36,ACH-001626,PT-CVPxmk,OSC-20,OSC20,Oral Cavity Squamous Cell Carcinoma
37,ACH-001675,PT-6uEn4i,TR146,TR146,Oral Cavity Squamous Cell Carcinoma
38,ACH-001690,PT-uLUnir,UPCI-SCC-026,UPCISCC026,Oral Cavity Squamous Cell Carcinoma
39,ACH-001691,PT-km3C7x,UPCI-SCC-029A,UPCISCC029A,Oral Cavity Squamous Cell Carcinoma
40,ACH-001692,PT-pvMW8r,UPCI-SCC-040,UPCISCC040,Oral Cavity Squamous Cell Carcinoma
41,ACH-001694,PT-GgnlK1,UPCI-SCC-074,UPCISCC074,Oral Cavity Squamous Cell Carcinoma
42,ACH-001696,PT-YWwuRp,UPCI-SCC-111,UPCISCC111,Oral Cavity Squamous Cell Carcinoma
43,ACH-001698,PT-sxiEGA,UPCI-SCC-116,UPCISCC116,Oral Cavity Squamous Cell Carcinoma
44,ACH-001699,PT-uhmv08,UPCI-SCC-131,UPCISCC131,Oral Cavity Squamous Cell Carcinoma
45,ACH-001701,PT-CvPqts,UPCI-SCC-200,UPCISCC200,Oral Cavity Squamous Cell Carcinoma
46,ACH-002029,PT-rJXazG,SAS,SAS,Oral Cavity Squamous Cell Carcinoma
47,ACH-002043,PT-gB4Jfi,Ca9-22,CA922,Oral Cavity Squamous Cell Carcinoma
48,ACH-002045,PT-a3mx1w,HO-1-u-1,HO1U1,Oral Cavity Squamous Cell Carcinoma
49,ACH-002213,PT-2UHafq,BB49-HNC,BB49HNC,Oral Cavity Squamous Cell Carcinoma
50,ACH-002244,PT-vSXKPA,HO-1-N-1,HO1N1,Oral Cavity Squamous Cell Carcinoma
51,ACH-002295,PT-BYyQBX,PCI-30,PCI30,Oral Cavity Squamous Cell Carcinoma
52,ACH-002296,PT-oqands,PCI-38,PCI38,Oral Cavity Squamous Cell Carcinoma
53,ACH-002298,PT-mnzvO8,PCI-6A,PCI6A,Oral Cavity Squamous Cell Carcinoma
54,ACH-002305,PT-ErYkxf,SKN-3,SKN3,Oral Cavity Squamous Cell Carcinoma

In [ ]:
# Extract filtered_arranged_table.cs matching with Oral_Squamous_Cell_Carcinoma CCL (Cancer Cell Line) to have filtered_arranged_table_Oral_Squamous.csv

import pandas as pd

# Read file 1
file1_path = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
file1_df = pd.read_csv(file1_path)

# Read file 2
file2_path = '/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/Oral_Squamous_Cell_Carcinoma.csv'
file2_df = pd.read_csv(file2_path)

# Get the matching rows from file 1
filtered_arranged_table_Oral_Squamous = file1_df[file1_df['DepMap_ID'].isin(file2_df['ModelID'])]

# Save the filtered_arranged_table_Oral_Squamou DataFrame to a CSV file
filtered_arranged_table_Oral_Squamous.to_csv("/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/filtered_arranged_table_Oral_Squamous.csv", index=False)

# Display filtered_arranged_table_Oral_Squamous
filtered_arranged_table_Oral_Squamous

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,...,ZYG11A (440590) Exp,ZYG11B (79699) Exp,ZYX (7791) Exp,ZZEF1 (23140) Exp,ZZZ3 (26009) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
99,ACH-000181,4.238023,0.056584,0.111031,4.206331,0.000000,5.802193,0.042644,4.758623,4.022368,...,2.313246,2.462052,5.465974,4.342697,3.725741,0.074646,0.999686,0.267469,1.000000,0.080037
103,ACH-000188,2.432959,0.014355,0.189034,0.298658,0.000000,3.928844,0.028569,5.015694,3.403268,...,0.014355,1.097611,5.661921,2.650765,2.185867,0.052718,0.961044,0.094218,0.963732,0.068937
128,ACH-000228,5.128871,0.014355,0.150560,3.758090,0.056584,5.972233,0.000000,5.498570,4.773996,...,1.422233,2.330558,6.575766,3.486714,2.691534,0.156112,0.988692,0.070409,0.993455,0.036775
135,ACH-000238,3.117695,0.070389,0.163499,4.870858,0.000000,5.693766,0.250962,5.144862,3.732269,...,0.028569,1.970854,5.786335,2.847997,4.270529,0.010761,0.997741,0.039210,0.997330,0.026842
296,ACH-000472,0.555816,0.028569,0.189034,0.650765,0.000000,2.195348,0.084064,4.704872,3.203201,...,0.584963,1.454176,5.126808,3.407353,3.764474,0.078337,0.999853,0.107000,0.999991,0.072139
321,ACH-000503,2.809414,0.028569,0.124328,4.440952,0.000000,4.280956,0.000000,4.626439,4.581954,...,0.963474,2.192194,6.153197,3.140779,3.288359,0.036254,1.000000,0.038261,0.999988,0.019149
331,ACH-000518,0.632268,0.014355,0.042644,0.250962,0.000000,5.150966,0.176323,5.780573,3.709291,...,0.286881,2.801159,6.649615,4.120186,3.599318,0.049299,0.997556,0.057228,0.996603,0.055766
347,ACH-000546,0.475085,0.042644,0.150560,0.713696,0.000000,4.104337,0.475085,5.367022,4.557655,...,0.214125,2.613532,4.647315,3.802193,3.825786,0.045031,0.999991,0.032847,0.999925,0.033679
349,ACH-000548,2.859970,0.014355,0.422233,2.797013,0.000000,4.319762,0.356144,5.359310,4.672425,...,0.028569,1.970854,6.375561,3.693766,3.690417,0.099956,1.000000,0.256338,1.000000,0.052276
390,ACH-000606,0.333424,0.000000,0.201634,0.739848,0.000000,3.430285,0.000000,5.051372,3.393691,...,0.042644,2.042644,5.304511,2.931683,3.382667,0.008650,0.986207,0.018890,0.975153,0.038666
397,ACH-000619,0.000000,0.000000,0.214125,0.545968,0.000000,4.640968,0.028569,4.741467,4.262283,...,0.084064,2.250962,5.275007,3.543496,3.544733,0.132590,0.999155,0.084790,0.999878,0.037580
404,ACH-000630,1.090853,0.014355,1.851999,0.014355,0.000000,5.085340,0.124328,5.042644,5.022368,...,0.097611,4.297191,7.067488,4.625855,4.513491,0.140950,0.997185,0.162245,0.999755,0.050641
468,ACH-000732,2.568032,0.000000,0.298658,0.333424,0.000000,2.107688,0.042644,4.370862,3.648465,...,0.014355,1.831877,5.949068,2.731183,3.163499,0.039239,0.556178,0.033627,0.973770,0.021144
470,ACH-000735,0.189034,0.014355,0.150560,0.189034,0.000000,3.738768,0.042644,5.073820,4.909773,...,0.056584,2.353323,5.420213,3.140779,3.270529,0.048555,0.986994,0.069107,0.999594,0.062425
474,ACH-000740,2.469886,0.000000,0.150560,1.298658,0.150560,5.203201,0.000000,5.283551,4.356144,...,2.189034,2.384050,5.036943,3.601697,3.504620,0.033268,0.998778,0.132945,0.972437,0.113020
494,ACH-000771,1.735522,0.014355,0.070389,4.051372,0.000000,4.393004,0.014355,3.385431,3.601697,...,0.084064,2.144046,6.427271,2.526069,2.944858,0.077380,0.999867,0.130270,0.999841,0.021452
500,ACH-000778,0.000000,0.000000,0.000000,0.014355,0.000000,0.475085,0.000000,4.895787,4.135863,...,1.565597,2.378512,6.011898,3.450221,4.454834,0.018133,0.996739,0.055651,0.997281,0.040480
512,ACH-000794,3.368768,0.028569,0.056584,6.691813,0.000000,4.194560,0.014355,3.524816,4.238023,...,0.669027,1.682573,5.636045,3.319040,2.904966,0.177959,0.999957,0.129195,0.999997,0.047290
536,ACH-000832,0.000000,0.028569,0.014355,0.765535,0.084064,3.740928,0.000000,5.118941,4.536675,...,0.124328,2.408712,5.882154,3.528571,4.011675,0.047996,0.995824,0.116863,0.999684,0.023827
540,ACH-000836,0.669027,0.000000,0.310340,0.275007,0.000000,1.195348,0.042644,5.192983,4.230357,...,1.682573,2.627607,5.562242,3.158660,4.238787,0.076620,0.980912,0.052839,0.999034,0.019017
694,ACH-001228,2.963474,0.000000,0.189034,0.731183,0.163499,4.077243,0.042644,5.511911,3.168321,...,2.722466,2.729009,3.987321,2.173127,4.335569,0.013649,0.523671,0.180687,0.999958,0.016952
695,ACH-001229,0.124328,0.000000,0.000000,0.097611,0.014355,3.780310,0.000000,4.448901,3.635754,...,1.137504,1.963474,5.849499,2.456806,3.688180,0.050424,0.974492,0.098051,0.967259,0.026408
718,ACH-001332,3.842979,0.000000,0.070389,4.853497,0.000000,4.208673,0.000000,5.154616,3.658783,...,0.659925,1.594549,4.851499,2.553361,3.683696,0.093590,0.998737,0.046992,0.999535,0.008948
728,ACH-001346,0.070389,0.014355,0.000000,3.504620,0.000000,4.282440,0.137504,5.074249,5.018812,...,0.028569,2.392317,5.924813,2.895303,4.037382,0.043066,1.000000,0.065044,0.999964,0.017843
729,ACH-001347,2.467279,0.000000,0.042644,5.655352,0.000000,5.690976,0.000000,4.590362,4.090007,...,0.042644,2.367371,7.249161,2.963474,3.806324,0.023893,0.995177,0.207386,0.999828,0.060235
791,ACH-001509,0.124328,0.028569,0.000000,3.107688,0.000000,5.355087,0.000000,4.093391,3.942045,...,0.028569,1.356144,5.250583,2.207893,3.849999,0.052870,0.999631,0.079011,0.999250,0.029486
792,ACH-001510,2.724650,0.000000,0.028569,0.124328,0.000000,3.946731,0.000000,3.841973,3.658783,...,0.000000,0.695994,5.957218,1.182692,2.513491,0.019146,0.941331,0.138102,0.941332,0.053745
793,ACH-001511,2.350497,0.014355,0.000000,4.642702,0.000000,5.139551,0.014355,5.275752,3.714795,...,0.799087,2.056584,6.144046,2.877744,3.475085,0.034539,0.999948,0.061527,0.999973,0.060868
813,ACH-001542,0.000000,0.000000,0.000000,0.000000,0.000000,3.656496,0.000000,4.842476,3.568032,...,0.028569,1.765535,5.905206,1.464668,3.295723,0.180406,0.999152,0.111343,0.988387,0.013726
814,ACH-001543,2.333424,0.000000,0.000000,2.935460,0.000000,4.038261,0.084064,5.200850,3.147307,...,0.070389,1.416840,6.215679,2.358959,4.401221,0.008448,0.895431,0.058668,0.996576,0.019537
849,ACH-001625,0.344828,0.014355,0.014355,1.859970,0.000000,4.117695,0.000000,5.339494,3.346248,...,0.443607,2.313246,6.204767,3.132577,3.632268,0.007218,0.971423,0.239806,0.999988,0.110413
850,ACH-001626,0.163499,0.000000,0.214125,0.214125,0.000000,2.855990,0.056584,5.484138,4.238787,...,1.104337,2.192194,5.386811,2.904966,3.673556,0.062046,1.000000,0.069883,1.000000,0.029165
878,ACH-001690,0.000000,0.000000,0.000000,0.526069,0.000000,4.009885,0.000000,4.280214,2.283922,...,0.000000,0.992768,5.332350,1.952334,4.003602,0.116615,0.989384,0.207571,0.995289,0.094681
879,ACH-001692,0.000000,0.000000,0.000000,1.035624,0.000000,2.516015,0.000000,3.877744,3.117695,...,0.014355,2.185867,5.750070,2.344828,3.700440,0.076363,0.990780,0.228601,0.984635,0.105229
880,ACH-001694,1.327687,0.000000,0.000000,0.000000,0.000000,4.635174,0.000000,3.217231,3.395063,...,0.014355,2.599318,6.155628,3.489286,4.823749,0.051191,0.987464,0.201271,0.980190,0.010562
881,ACH-001696,3.157044,0.000000,0.000000,0.443607,0.000000,1.974529,0.000000,4.193772,2.889474,...,0.124328,0.863938,6.097611,1.292782,1.735522,0.044380,0.992959,0.103558,0.979592,0.056723
882,ACH-001698,0.839960,0.000000,0.356144,0.799087,0.000000,1.495695,0.000000,4.043519,2.405992,...,0.000000,0.871844,4.336997,1.238787,2.875780,0.035587,0.999816,0.078213,0.999710,0.028752
883,ACH-001699,0.042644,0.000000,0.000000,0.985500,0.000000,3.874797,0.000000,3.536053,3.072106,...,0.111031,1.464668,6.366497,1.859970,3.003602,0.681202,0.998855,0.110405,0.999681,0.020458
884,ACH-001701,0.028569,0.000000,0.111031,2.666757,0.000000,2.847997,0.000000,4.958843,3.886550,...,0.124328,1.695994,5.618239,3.204767,3.381283,0.142208,0.999992,0.025330,0.999974,0.008304
960,ACH-002029,0.000000,0.000000,1.189034,0.000000,0.000000,2.367371,0.000000,5.485105,4.238023,...,0.000000,2.575312,5.732269,2.553361,4.410070,0.105691,0.998753,0.137715,0.995690,0.016159
965,ACH-002045,0.275007,0.000000,0.000000,0.871844,0.000000,3.819668,0.000000,4.286142,4.575312,...,0.000000,2.518535,5.084064,2.319040,3.357552,0.030359,0.980596,0.017755,0.991391,0.027967

In [ ]:
import pandas as pd

# Read file 1
file1_path = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
file1_df = pd.read_csv(file1_path)

# Read file 2
file2_path = '/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/Oral Cavity Squamous Cell Carcinoma.csv'
file2_df = pd.read_csv(file2_path)

# Merge the data frames based on the first column (DepMap_ID and ModelID)
merged_df = pd.merge(file1_df, file2_df, left_on='DepMap_ID', right_on='ModelID')

# Save the merged data to a new CSV file
output_path = '/content/drive/MyDrive/Colab Notebooks/merged_data.csv'
merged_df.to_csv(output_path, index=False)

In [ ]:
# checking some columns values

import pandas as pd

# Load the CSV file into a DataFrame
filtered_arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")

# Select the desired columns
selected_columns = filtered_arranged_table[["AAK1 (22848) Exp","ABCA4 (24) Exp","ACER3 (55331) Exp"]]

# Display the selected columns
selected_columns

      AAK1 (22848) Exp  ABCA4 (24) Exp  ACER3 (55331) Exp
0             3.078951        2.443607           5.980025
1             2.292782        0.713696           3.648465
2             2.625270        0.163499           4.025029
3             1.970854        0.070389           2.283922
4             3.397803        0.070389           3.549669
...                ...             ...                ...
1000          3.819668        0.238787           2.313246
1001          4.034744        1.967169           3.206331
1002          4.133399        1.786596           2.799087
1003          3.396434        0.400538           6.646451
1004          3.033863        0.000000           3.496974

[1005 rows x 3 columns]

In [ ]:
# checking some columns values

import pandas as pd

# Load the CSV file into a DataFrame
filtered_arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")

# Select columns based on partial names
selected_columns = filtered_arranged_table.filter(like="AAK1")
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="ABCA4"))
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="ACER3"))

# Display the selected columns
selected_columns

      AAK1 (22848) Exp  ABCA4 (24) Exp  ACER3 (55331) Exp
0             3.078951        2.443607           5.980025
1             2.292782        0.713696           3.648465
2             2.625270        0.163499           4.025029
3             1.970854        0.070389           2.283922
4             3.397803        0.070389           3.549669
...                ...             ...                ...
1000          3.819668        0.238787           2.313246
1001          4.034744        1.967169           3.206331
1002          4.133399        1.786596           2.799087
1003          3.396434        0.400538           6.646451
1004          3.033863        0.000000           3.496974

[1005 rows x 3 columns]

In [ ]:
# From correlation_table_diavalues_gt_0.csv which extract the diagonal values bigger than 0.1 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_diavalues_gt_0.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,AAK1 (22848) Exp,ABCA4 (24) Exp,ABCB6 (10058) Exp,ABCD3 (5825) Exp,ABI2 (10152) Exp,ABLIM2 (84448) Exp,ACAD8 (27034) Exp,ACAP3 (116983) Exp,ACER3 (55331) Exp,...,ZNF862 (643641) Exp,ZNFX1 (57169) Exp,ZRANB2 (9406) Exp,ZYG11B (79699) Exp,ZYX (7791) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,3.078951,2.443607,4.811985,4.746313,5.388534,1.510962,2.918386,4.514753,5.980025,...,2.629939,4.003602,6.157044,2.797013,6.821455,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,2.292782,0.713696,4.973152,4.727920,5.187055,0.000000,6.191997,3.166715,3.648465,...,1.560715,2.904966,7.344917,2.032101,7.002252,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,2.625270,0.163499,5.231509,5.802452,5.328406,0.028569,5.561632,2.464668,4.025029,...,1.700440,3.166715,7.609179,2.761285,6.826421,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.970854,0.070389,3.392317,4.532940,3.499527,2.386811,4.410070,4.799605,2.283922,...,2.435629,3.051372,5.645010,1.989139,6.332708,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.397803,0.070389,5.590662,5.454834,4.841470,0.084064,5.183883,4.221877,3.549669,...,1.395063,4.263786,5.151372,2.956057,7.853185,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,3.819668,0.238787,3.730096,5.890933,5.172728,0.189034,2.695994,1.895303,2.313246,...,2.773996,4.753284,6.036064,4.173127,6.560256,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.034744,1.967169,2.805292,5.292414,4.761817,0.731183,4.161081,1.910733,3.206331,...,2.408712,3.614710,5.499846,3.084064,6.596935,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.133399,1.786596,3.226509,4.999098,4.737146,0.214125,3.351911,2.464668,2.799087,...,0.887525,4.932156,5.254367,2.568032,6.953498,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.396434,0.400538,3.379898,4.888500,4.164304,0.042644,2.482848,3.649615,6.646451,...,1.925999,3.484138,5.189825,2.748461,7.432041,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.033863,0.000000,4.672991,4.822730,4.914565,0.000000,3.509696,3.845992,3.496974,...,2.516015,3.512227,5.825531,2.776104,5.182295,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# From correlation_table_A1BG_gt_01.csv which extract the ALL values bigger than 0.1 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/correlation_table_A1BG_gt_01.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/A1BG_gt_01.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,ABCA3 (21) Exp,ADAMTS7 (11173) Exp,AKIP1 (56672) Exp,AP2A2 (161) Exp,ARL8A (127829) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,1.646163,1.541019,5.518850,4.445594,4.624101,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,1.350497,1.339137,4.385431,3.992768,4.889960,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,1.933573,0.584963,4.482203,4.223423,4.187451,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,0.400538,0.124328,5.092969,4.556429,4.340562,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.419539,0.056584,5.040454,5.514753,3.622930,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,2.017922,0.389567,4.307429,4.482203,3.384050,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,2.459432,1.981853,4.211791,4.054848,3.933573,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,0.042644,2.592158,4.595742,4.835924,3.739848,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,0.526069,2.049631,5.684538,4.199280,4.606442,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,0.111031,1.090853,4.645010,3.563158,3.760221,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# checking some columns values wheather they are matched

import pandas as pd

# Load the CSV file into a DataFrame
filtered_arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")

# Select columns based on partial names
selected_columns = filtered_arranged_table.filter(like="ABCA7")
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="ACSL5"))
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="AKIP1"))
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="AP2A2"))
selected_columns = selected_columns.join(filtered_arranged_table.filter(like="ARL8A"))

# Display the selected columns
selected_columns

,ABCA7 (10347) Exp,ACSL5 (51703) Exp,AKIP1 (56672) Exp,AP2A2 (161) Exp,ARL8A (127829) Exp
0,2.121015,0.226509,5.518850,4.445594,4.624101
1,4.883132,4.942984,4.385431,3.992768,4.889960
2,3.475085,5.008989,4.482203,4.223423,4.187451
3,3.898208,6.969012,5.092969,4.556429,4.340562
4,3.351911,4.430954,5.040454,5.514753,3.622930
...,...,...,...,...,...
1000,1.280956,2.277985,4.307429,4.482203,3.384050
1001,2.620586,1.201634,4.211791,4.054848,3.933573
1002,2.523562,1.599318,4.595742,4.835924,3.739848
1003,2.794936,1.769772,5.684538,4.199280,4.606442
1004,1.097611,5.550285,4.645010,3.563158,3.760221

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_gt_01.csv which extract the all values bigger than 0.1 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_gt_01.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/{gene_name}_gt_01.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_gt_01.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_gt_01.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_gt_01.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_gt_01.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_gt_01.csv

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_gt_01.csv which extract the all values bigger than 0.1 and then file filtered_arranged_table_Oral_Squamous.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_gt_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_gt_01.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/filtered_arranged_table_Oral_Squamous.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/{gene_name}_Oral_Squamous_gt_01.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/EIF2AK3_Oral_Squamous_gt_01.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/MYC_Oral_Squamous_gt_01.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/NQO1_Oral_Squamous_gt_01.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SF3B1_Oral_Squamous_gt_01.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SQSTM1_Oral_Squamous_gt_01.csv

In [ ]:
# Checking datasets

import pandas as pd

EIF2AK3_Oral_Squamous_gt_01 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/EIF2AK3_Oral_Squamous_gt_01.csv")

EIF2AK3_Oral_Squamous_gt_01

,DepMap_ID,ABCA12 (26154) Exp,ATG3 (64422) Exp,BCL2A1 (597) Exp,EGR3 (1960) Exp,FYB1 (2533) Exp,GFM1 (85476) Exp,HCLS1 (3059) Exp,KRR1 (11103) Exp,LAMB4 (22798) Exp,...,RPS19BP1 (91582) Exp,RPS6KA5 (9252) Exp,TBRG4 (9238) Exp,TMEM229B (161145) Exp,UTP4 (84916) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000181,4.316870,4.746850,0.333424,0.895303,3.061776,4.560104,0.400538,5.502712,0.163499,...,5.633141,1.028569,6.449561,1.014355,4.895787,0.074646,0.999686,0.267469,1.000000,0.080037
1,ACH-000188,0.097611,5.053980,0.475085,0.871844,2.153805,4.647315,4.489286,5.901832,0.070389,...,5.563158,1.124328,5.394034,2.456806,5.232277,0.052718,0.961044,0.094218,0.963732,0.068937
2,ACH-000228,3.404631,5.759156,0.799087,0.773996,2.319040,5.582255,1.056584,5.243364,0.163499,...,6.366322,2.560715,6.036503,1.664483,5.879706,0.156112,0.988692,0.070409,0.993455,0.036775
3,ACH-000238,1.589763,5.548128,0.214125,0.356144,4.626439,4.815063,1.117695,5.646163,0.555816,...,6.567424,1.594549,6.566815,1.176323,5.674969,0.010761,0.997741,0.039210,0.997330,0.026842
4,ACH-000472,0.941106,5.021480,0.042644,0.722466,4.086614,4.634012,4.534809,4.475085,0.028569,...,5.765004,1.516015,5.267161,0.659925,4.620586,0.078337,0.999853,0.107000,0.999991,0.072139
5,ACH-000503,1.803227,5.370513,0.321928,0.201634,1.035624,3.240314,0.201634,4.585563,0.111031,...,5.890447,2.269033,6.114367,0.070389,5.715344,0.036254,1.000000,0.038261,0.999988,0.019149
6,ACH-000518,1.778209,5.567424,1.182692,0.464668,4.240314,4.860466,0.650765,4.514753,0.356144,...,5.880930,2.555816,7.643279,2.408712,4.954662,0.049299,0.997556,0.057228,0.996603,0.055766
7,ACH-000546,0.863938,5.023699,0.056584,0.321928,0.687061,5.111031,0.286881,4.997292,0.124328,...,5.507478,2.438293,5.937815,1.687061,4.920770,0.045031,0.999991,0.032847,0.999925,0.033679
8,ACH-000548,0.941106,5.015248,3.555816,1.070389,7.886001,4.175525,6.715893,4.919817,0.321928,...,5.576824,2.742006,6.483010,2.422233,5.145677,0.099956,1.000000,0.256338,1.000000,0.052276
9,ACH-000606,1.310340,6.118526,0.978196,1.104337,3.169925,5.091700,0.176323,5.442612,0.097611,...,6.382667,3.003602,6.821328,3.665620,6.045268,0.008650,0.986207,0.018890,0.975153,0.038666
10,ACH-000619,1.526069,5.247168,0.124328,0.903038,3.731183,5.167519,3.459432,4.956521,0.378512,...,5.397461,2.094236,5.806324,0.650765,5.668460,0.132590,0.999155,0.084790,0.999878,0.037580
11,ACH-000630,0.028569,5.058749,0.000000,0.632268,2.032101,5.507795,0.464668,5.597531,0.214125,...,5.646451,2.217231,5.959075,1.007196,5.795715,0.140950,0.997185,0.162245,0.999755,0.050641
12,ACH-000732,1.384050,4.747924,2.472488,0.056584,3.179511,3.527321,1.007196,4.728465,0.150560,...,5.888987,0.799087,4.560104,1.416840,4.617651,0.039239,0.556178,0.033627,0.973770,0.021144
13,ACH-000735,0.687061,5.926711,3.179511,0.545968,4.467932,4.796494,4.420213,5.000000,0.226509,...,5.548128,1.469886,5.417177,2.097611,5.707911,0.048555,0.986994,0.069107,0.999594,0.062425
14,ACH-000740,1.214125,5.410748,0.000000,0.163499,0.298658,5.530445,0.263034,5.197708,0.604071,...,6.562548,2.680324,6.940167,0.584963,5.969243,0.033268,0.998778,0.132945,0.972437,0.113020
15,ACH-000771,3.598127,4.921722,1.495695,1.891419,3.995485,3.805292,0.333424,3.845992,0.028569,...,5.024142,1.195348,4.601697,0.941106,3.984589,0.077380,0.999867,0.130270,0.999841,0.021452
16,ACH-000778,0.263034,6.208868,1.718088,0.070389,1.226509,5.705149,4.649041,6.368245,0.678072,...,6.057234,2.003602,6.461561,2.247928,6.321207,0.018133,0.996739,0.055651,0.997281,0.040480
17,ACH-000794,2.809414,4.539159,1.560715,0.505891,3.458119,4.904484,0.622930,4.228819,0.056584,...,5.017477,1.664483,4.493135,1.292782,4.112700,0.177959,0.999957,0.129195,0.999997,0.047290
18,ACH-000832,1.959770,6.278357,1.899176,0.298658,4.233428,5.340918,3.640390,4.885574,0.000000,...,5.510962,3.243364,6.874182,2.589763,5.756756,0.047996,0.995824,0.116863,0.999684,0.023827
19,ACH-000836,0.321928,6.123914,2.405992,0.056584,2.726831,6.091700,6.757157,5.861459,0.000000,...,6.672142,2.375735,5.857981,1.021480,5.982309,0.076620,0.980912,0.052839,0.999034,0.019017
20,ACH-001228,1.367371,6.305059,0.000000,0.713696,0.000000,5.902797,0.238787,5.492174,0.000000,...,5.602588,2.655352,5.199280,0.495695,5.551208,0.013649,0.523671,0.180687,0.999958,0.016952
21,ACH-001229,0.782409,5.536675,1.875780,0.137504,5.285032,4.081510,0.275007,5.363171,0.000000,...,6.166113,1.952334,4.886550,0.286881,4.072963,0.050424,0.974492,0.098051,0.967259,0.026408
22,ACH-001332,1.748461,5.591859,0.028569,0.765535,2.173127,5.446918,0.695994,4.946263,0.757023,...,5.928844,1.292782,6.447083,0.286881,5.415150,0.093590,0.998737,0.046992,0.999535,0.008948
23,ACH-001346,2.684819,5.020147,0.286881,0.250962,1.871844,5.380245,0.454176,4.859970,0.111031,...,6.466627,1.887525,5.749534,0.847997,4.907371,0.043066,1.000000,0.065044,0.999964,0.017843
24,ACH-001347,3.811471,5.490249,0.056584,0.238787,5.874059,4.791814,0.713696,4.742545,0.070389,...,5.873075,1.292782,5.951401,0.790772,4.896272,0.023893,0.995177,0.207386,0.999828,0.060235
25,ACH-001509,2.266037,4.313246,0.389567,0.443607,3.777157,4.381283,0.731183,3.863938,0.042644,...,5.339137,0.773996,5.397118,0.389567,3.999098,0.052870,0.999631,0.079011,0.999250,0.029486
26,ACH-001510,0.250962,4.421560,1.333424,0.137504,2.313246,3.648465,0.028569,3.797013,0.014355,...,5.629357,0.333424,5.581050,0.389567,3.035624,0.019146,0.941331,0.138102,0.941332,0.053745
27,ACH-001511,2.046142,5.671576,0.097611,0.028569,1.948601,4.496974,1.459432,5.235727,5.081936,...,6.686220,0.773996,5.760753,0.028569,4.987321,0.034539,0.999948,0.061527,0.999973,0.060868
28,ACH-001542,0.333424,5.461070,0.124328,0.042644,5.151778,4.318317,3.887525,4.649615,0.028569,...,6.305606,1.042644,5.198887,2.007196,6.065012,0.180406,0.999152,0.111343,0.988387,0.013726
29,ACH-001543,0.622930,5.223809,0.000000,0.150560,4.666757,4.779260,0.111031,4.136684,0.056584,...,5.897966,1.182692,5.465322,0.137504,5.095503,0.008448,0.895431,0.058668,0.996576,0.019537
30,ACH-001625,2.144046,5.454176,0.432959,0.070389,4.338424,6.038041,4.736064,5.718088,0.536053,...,6.326609,1.933573,6.337354,0.275007,6.073606,0.007218,0.971423,0.239806,0.999988,0.110413
31,ACH-001626,0.226509,5.526069,0.111031,0.669027,0.189034,4.640390,0.163499,5.161888,0.214125,...,4.853996,1.490570,6.908693,2.014355,4.785027,0.062046,1.000000,0.069883,1.000000,0.029165
32,ACH-001690,0.516015,6.055282,2.144046,0.028569,5.224966,4.816600,5.018812,4.996841,0.176323,...,5.183487,0.903038,4.931683,1.761285,4.834408,0.116615,0.989384,0.207571,0.995289,0.094681
33,ACH-001692,0.555816,5.750339,0.575312,0.097611,5.042207,4.346957,0.084064,5.232277,0.014355,...,5.239551,1.956057,5.680606,1.400538,5.175125,0.076363,0.990780,0.228601,0.984635,0.105229
34,ACH-001694,3.542258,6.203593,4.862947,1.411426,7.867341,5.165912,6.899659,5.806840,0.201634,...,5.768714,3.241840,5.236875,3.961623,4.559492,0.051191,0.987464,0.201271,0.980190,0.010562
35,ACH-001696,0.226509,3.793896,1.859970,0.028569,5.591560,2.650765,0.000000,3.481557,0.070389,...,5.115616,0.536053,4.742545,1.201634,3.420887,0.044380,0.992959,0.103558,0.979592,0.056723
36,ACH-001698,1.182692,4.807870,0.056584,0.014355,0.176323,3.082362,0.201634,4.712045,0.400538,...,4.775577,0.495695,5.340918,0.070389,4.397118,0.035587,0.999816,0.078213,0.999710,0.028752
37,ACH-001699,1.803227,5.181898,2.778209,0.111031,4.462052,4.224966,0.575312,4.994127,0.000000,...,5.022368,2.150560,4.990955,1.176323,5.010780,0.681202,0.998855,0.110405,0.999681,0.020458
38,ACH-001701,2.980025,4.320485,0.000000,1.169925,3.930737,4.279471,0.400538,5.612058,0.163499,...,5.470862,1.811471,5.512543,1.636915,3.996389,0.142208,0.999992,0.025330,0.999974,0.008304
39,ACH-002029,0.632268,6.247168,0.000000,1.021480,0.250962,5.850249,0.687061,5.274262,0.956057,...,5.412443,1.963474,6.055716,0.163499,6.093180,0.105691,0.998753,0.137715,0.995690,0.016159
40,ACH-002045,2.298658,5.347311,0.070389,0.014355,1.914565,5.629648,0.286881,5.538849,0.042644,...,5.588265,2.485427,6.272023,0.014355,5.594549,0.030359,0.980596,0.017755,0.991391,0.027967

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_gt_00.csv which extract the all values bigger than 0 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_gt_00.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/{gene_name}_gt_00.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_gt_00.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_gt_00.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_gt_00.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_gt_00.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_gt_00.csv

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_gt_00.csv which extract the all values bigger than 0 and then file filtered_arranged_table_Oral_Squamous.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_gt_00.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_gt_00.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/filtered_arranged_table_Oral_Squamous.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/{gene_name}_Oral_Squamous_gt_00.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/EIF2AK3_Oral_Squamous_gt_00.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/MYC_Oral_Squamous_gt_00.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/NQO1_Oral_Squamous_gt_00.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SF3B1_Oral_Squamous_gt_00.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SQSTM1_Oral_Squamous_gt_00.csv

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_ng_01.csv which extract the all values less than -0.1 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_ng_01.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/{gene_name}_ng_01.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_ng_01.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_ng_01.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_ng_01.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_ng_01.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_ng_01.csv

In [ ]:
## From 'EIF2AK3 (9451) Dep', 'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep', 'SQSTM1 (8878) Dep_ng_01.csv which extract the all values bigger than 0 and then file filtered_arranged_table_Oral_Squamous.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Define the input file paths for the first files
first_file_paths = [
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/EIF2AK3_(9451)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_(4609)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/NQO1_(1728)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SF3B1_(23451)_Dep_ng_01.csv',
    '/content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/SQSTM1_(8878)_Dep_ng_01.csv'
]

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/filtered_arranged_table_Oral_Squamous.csv'
df_second = pd.read_csv(second_file)

# Iterate over the first files and generate corresponding output files
for file_path in first_file_paths:
    # Read the first file and extract the row names as a list
    df_first = pd.read_csv(file_path)
    row_names = list(df_first.iloc[:, 0])

    # Filter columns from the second file based on matching row names
    columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
    df_filtered = df_second[columns_to_keep]

    # Extract the gene name from the first file path
    gene_name = file_path.split('/')[-1].split('_')[0]

    # Save the modified second file as the corresponding output file
    output_file = f'/content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/{gene_name}_Oral_Squamous_ng_01.csv'
    df_filtered.to_csv(output_file, index=False)

    print(f"Saved filtered DataFrame for {gene_name} to {output_file}")

Saved filtered DataFrame for EIF2AK3 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/EIF2AK3_Oral_Squamous_ng_01.csv
Saved filtered DataFrame for MYC to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/MYC_Oral_Squamous_ng_01.csv
Saved filtered DataFrame for NQO1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/NQO1_Oral_Squamous_ng_01.csv
Saved filtered DataFrame for SF3B1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SF3B1_Oral_Squamous_ng_01.csv
Saved filtered DataFrame for SQSTM1 to /content/drive/MyDrive/Colab Notebooks/Oral_Squamous_Cell_Carcinoma/SQSTM1_Oral_Squamous_ng_01.csv

In [ ]:
# Checking datasets

import pandas as pd

modified_table = pd.read_csv("//content/drive/MyDrive/Colab Notebooks/correlation_table_filter_all/MYC_gt_01.csv")
modified_table

,DepMap_ID,ABCA7 (10347) Exp,ABCB11 (8647) Exp,ABHD14B (84836) Exp,ABHD3 (171586) Exp,ABI1 (10006) Exp,ABRA (137735) Exp,ACAA1 (30) Exp,ACSF3 (197322) Exp,ACSL5 (51703) Exp,...,ZNF296 (162979) Exp,ZNF341 (84905) Exp,ZNF706 (51123) Exp,ZP3 (7784) Exp,ZPBP2 (124626) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,2.121015,0.014355,4.179511,3.021480,3.787641,0.028569,5.439956,3.542258,0.226509,...,0.748461,1.895303,6.191405,1.867896,0.000000,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,4.883132,0.275007,6.203397,2.682573,4.689299,0.000000,4.457463,4.875289,4.942984,...,4.012569,2.150560,6.282996,2.910733,0.000000,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,3.475085,0.189034,5.788686,3.754888,5.242603,0.056584,4.144046,4.606442,5.008989,...,3.072106,2.223423,6.970624,1.859970,0.189034,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,3.898208,0.014355,6.371907,4.418865,4.493775,0.014355,5.983450,3.868884,6.969012,...,2.090853,1.655352,5.641835,3.053111,0.000000,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.351911,0.000000,5.212180,4.241840,5.785289,0.000000,6.383877,4.201634,4.430954,...,2.094236,1.769772,6.298658,1.867896,0.000000,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,1.280956,0.000000,4.470537,4.308885,5.372256,0.000000,3.909773,3.478972,2.277985,...,0.000000,0.765535,6.785551,2.419539,0.000000,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,2.620586,0.014355,4.651339,2.353323,4.463361,0.000000,5.395406,3.229588,1.201634,...,0.176323,1.063503,5.784504,2.933573,0.028569,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,2.523562,0.000000,4.570463,3.612352,4.459432,0.000000,5.169123,3.935460,1.599318,...,0.422233,1.097611,5.563158,3.189034,0.000000,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,2.794936,0.000000,5.132577,3.428946,4.736064,0.014355,5.360013,2.341986,1.769772,...,0.344828,0.887525,7.288912,4.248687,0.000000,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,1.097611,0.014355,5.285032,4.262283,5.133399,0.028569,4.152183,2.946731,5.550285,...,0.000000,1.157044,7.774853,2.996389,0.000000,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# From correlation_table_diavalues_gt_03.csv which extract the diagonal values bigger than 0.3 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_diavalues_gt_03.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified_03.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,ARHGAP29 (9411) Exp,ARL4C (10123) Exp,BCAR1 (9564) Exp,BCAR3 (8412) Exp,BCL2 (596) Exp,BCL2L1 (598) Exp,CCND1 (595) Exp,CCND2 (894) Exp,CCND3 (896) Exp,...,YAP1 (10413) Exp,ZEB1 (6935) Exp,ZEB2 (9839) Exp,ZFP36L1 (677) Exp,ZNF217 (7764) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,7.570994,3.923149,4.506526,3.407353,0.903038,6.933573,7.437877,0.042644,4.375735,...,4.981853,0.124328,0.226509,5.612058,4.915999,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,0.189034,0.084064,0.250962,0.475085,1.361768,7.527399,1.056584,4.017031,9.091753,...,0.150560,0.176323,6.326609,4.339850,3.040892,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,0.263034,0.097611,0.214125,0.344828,2.536053,7.314787,2.295723,5.225352,8.802387,...,0.201634,0.555816,6.549207,4.202418,3.782409,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.855990,4.037382,4.491212,2.327687,0.150560,6.578335,5.198494,4.442943,4.533563,...,5.324091,0.650765,0.070389,6.787641,3.363171,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.635754,5.088311,5.914565,2.204767,1.378512,8.462748,7.428611,3.875780,4.568032,...,7.003040,0.070389,0.111031,4.984589,4.461398,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,6.633286,3.422233,2.541019,5.982537,0.985500,6.346070,5.191010,0.000000,4.560104,...,4.974988,5.261907,4.336997,6.478487,6.109570,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,5.783719,5.549977,3.618239,4.852998,0.985500,5.913608,6.467116,4.744699,5.634593,...,5.967399,4.552746,3.080658,6.238214,4.553361,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,5.003152,6.382667,4.006298,5.301222,1.250962,4.745775,6.474760,2.244887,6.387845,...,5.149341,3.415488,4.882643,6.464668,4.486714,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.976364,5.433961,4.526069,5.730368,1.356144,6.513491,10.967010,0.000000,5.676098,...,9.930811,3.286881,4.714246,5.561632,4.095080,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,2.189034,4.617063,2.244887,1.327687,4.367371,5.206331,8.036174,0.565597,4.807870,...,5.113117,0.042644,5.296090,6.658783,4.397803,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# From correlation_table_diavalues_gt_03.csv which extract the diagonal values bigger than 0.4 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_diavalues_gt_04.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified_04.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,ARHGAP29 (9411) Exp,BCAR3 (8412) Exp,CCND1 (595) Exp,CDK6 (1021) Exp,CFLAR (8837) Exp,EGFR (1956) Exp,FERMT2 (10979) Exp,FOSL1 (8061) Exp,GRHL2 (79977) Exp,...,WWTR1 (25937) Exp,YAP1 (10413) Exp,ZEB1 (6935) Exp,ZEB2 (9839) Exp,ZFP36L1 (677) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,7.570994,3.407353,7.437877,4.689299,3.857981,4.303781,4.574707,1.739848,4.307429,...,5.405992,4.981853,0.124328,0.226509,5.612058,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,0.189034,0.475085,1.056584,4.207112,5.255123,0.097611,3.229588,4.746850,0.028569,...,0.310340,0.150560,0.176323,6.326609,4.339850,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,0.263034,0.344828,2.295723,5.147307,5.192194,0.097611,3.552131,3.885574,0.042644,...,0.687061,0.201634,0.555816,6.549207,4.202418,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.855990,2.327687,5.198494,3.382667,3.485427,3.745237,0.028569,4.008092,3.283922,...,0.084064,5.324091,0.650765,0.070389,6.787641,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.635754,2.204767,7.428611,4.651339,6.191997,4.167519,4.758090,3.893362,4.430285,...,4.296457,7.003040,0.070389,0.111031,4.984589,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,6.633286,5.982537,5.191010,2.432959,4.671859,4.403268,7.198396,6.640245,0.014355,...,4.857981,4.974988,5.261907,4.336997,6.478487,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,5.783719,4.852998,6.467116,3.564378,5.441284,4.819668,4.416840,5.228819,0.526069,...,5.560715,5.967399,4.552746,3.080658,6.238214,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,5.003152,5.301222,6.474760,4.511595,4.040892,2.207893,6.463197,4.945327,0.000000,...,4.847997,5.149341,3.415488,4.882643,6.464668,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.976364,5.730368,10.967010,4.102658,4.913608,4.184280,5.046142,7.583233,0.000000,...,5.171127,9.930811,3.286881,4.714246,5.561632,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,2.189034,1.327687,8.036174,3.454176,4.610582,1.480265,3.995485,5.868143,0.000000,...,3.502076,5.113117,0.042644,5.296090,6.658783,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# From correlation_table_diavalues_ls_01.csv which extract the diagonal values less than -0.1 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_diavalues_ls_01.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified_neg01.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,ABCB7 (22) Exp,ABCC3 (8714) Exp,ABCE1 (6059) Exp,ABCF1 (23) Exp,ACD (65057) Exp,ADAMTS4 (9507) Exp,ADGRG1 (9289) Exp,ADGRL1 (22859) Exp,AEBP1 (165) Exp,...,ZNHIT1 (10467) Exp,ZPR1 (8882) Exp,ZW10 (9183) Exp,ZWILCH (55055) Exp,ZWINT (11130) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,4.771886,3.301588,6.037163,6.096979,4.281698,0.070389,7.974472,4.080658,2.942984,...,6.511120,5.062208,3.555816,5.080658,6.675957,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,4.238023,2.182692,5.823495,6.163297,4.773996,0.056584,4.462052,3.228049,4.210233,...,5.520422,7.055174,3.980939,4.276497,6.098664,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,4.621173,1.304511,6.767125,6.666899,4.838448,0.176323,5.222650,2.925999,4.403268,...,5.790772,6.824259,4.703765,5.628482,6.785289,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,3.582556,6.802064,5.558880,5.325530,4.427606,0.000000,6.840463,1.790772,0.111031,...,6.942866,4.624686,3.827819,3.842979,6.125775,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,4.415488,4.032101,6.666331,6.435128,5.087887,0.150560,6.183288,3.090853,0.070389,...,6.460906,6.683556,5.481880,4.761817,7.914086,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,4.857981,4.734981,6.394034,6.258707,3.171527,1.521051,2.873813,3.707083,0.189034,...,6.315965,4.087463,3.198494,5.974300,6.891662,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.744699,1.910733,5.635464,5.219169,3.682573,0.555816,4.175525,2.729009,6.462707,...,7.000789,5.187055,3.871844,4.839456,4.910733,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.505256,3.184280,7.266880,5.778997,3.339137,0.669027,3.072106,3.811471,5.985956,...,6.122880,4.292782,3.438293,3.816600,6.768846,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,4.067811,5.246788,5.988230,6.501758,3.415488,1.448901,5.782933,2.250962,6.649184,...,6.834281,4.211012,3.367371,4.788164,6.119771,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,4.609400,0.000000,6.083001,4.718088,3.095924,0.056584,5.413120,3.250962,7.380158,...,8.139398,5.822730,3.432959,3.702658,5.221877,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# From correlation_table_diavalues_ls_01.csv which extract the diagonal values less than -0.2 and then file filtered_arranged_table.csv mach gene EXP with it to produce a dataset for ML.

import pandas as pd

# Read the first file and extract the row names as a list
first_file = '/content/drive/MyDrive/Colab Notebooks/correlation_table_diavalues_ls_02.csv'
df_first = pd.read_csv(first_file)
row_names = list(df_first.iloc[:, 0])

# Read the second file and select columns with matching names
second_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv'
df_second = pd.read_csv(second_file)

# Filter columns from the second file based on matching row names
# columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]
columns_to_keep = ['DepMap_ID'] + [col for col in df_second.columns if col in row_names]+['EIF2AK3 (9451) Dep','MYC (4609) Dep','NQO1 (1728) Dep','SF3B1 (23451) Dep','SQSTM1 (8878) Dep']
df_filtered = df_second[columns_to_keep]

# Save the modified second file
output_file = '/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified_neg02.csv'
df_filtered.to_csv(output_file, index=False)

df_filtered

,DepMap_ID,AFAP1 (60312) Exp,AMOTL2 (51421) Exp,ARL14 (80117) Exp,ASH2L (9070) Exp,ATP6AP1 (537) Exp,ATP6AP2 (10159) Exp,BUD13 (84811) Exp,CCDC9B (388115) Exp,CDC26 (246184) Exp,...,VPS36 (51028) Exp,VPS53 (55275) Exp,WBP11 (51729) Exp,WTAP (9589) Exp,ZC3H13 (23091) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,5.688180,8.685975,0.731183,4.472488,6.839582,5.617651,3.628774,5.591859,5.505256,...,3.672425,3.396434,5.175125,5.189034,4.477030,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,0.422233,0.464668,0.028569,6.978768,5.953265,5.411765,5.162693,2.411426,4.891419,...,4.827311,2.893362,5.651052,6.123914,5.023699,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,0.941106,1.007196,0.000000,7.372256,5.149341,5.685380,5.738768,2.411426,5.638943,...,4.896272,3.261531,6.208673,6.774524,5.430285,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,2.809414,3.716991,3.171527,4.521679,5.107269,5.670444,3.920293,3.407353,5.894818,...,5.219169,3.600508,4.496974,5.173927,4.957450,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.662205,6.704734,1.827819,5.250962,6.882399,6.265474,5.113950,0.454176,5.853497,...,4.446256,3.775051,6.347311,6.415319,4.901591,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,5.814807,5.322649,0.124328,4.718088,7.028790,7.252003,3.171527,5.903038,6.277427,...,3.968091,3.518535,4.405312,5.870118,4.935460,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.435629,4.333424,2.042644,4.088311,6.672991,7.374953,4.046142,3.798051,6.473625,...,2.927896,4.269033,6.076602,5.941576,4.005400,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.187451,5.453847,1.613532,5.418527,7.327148,7.811471,3.699330,4.105175,5.463361,...,3.909773,3.419539,5.815832,6.072106,4.471838,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,4.386121,5.783980,0.443607,3.528571,6.568792,6.374170,3.165108,5.631395,5.782933,...,3.998196,3.713696,5.380937,6.124535,4.085765,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,2.107688,3.051372,0.000000,4.766065,6.703211,7.154919,3.275007,3.650765,4.815575,...,4.115200,3.566815,5.793376,4.763943,6.980597,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# Create a list of column names to preserve
preserved_columns = ["EIF2AK3", "SF3B1", "NQO1", "SQSTM1", "MYC", "HSP70"]

# Filter the columns based on the preserved column names
filtered_columns = [col for col in arranged_table_reordered.columns if ((col.endswith(" Dep") or col.endswith(" Exp")) and col.split(" ")[0] in preserved_columns) or (not col.endswith(" Dep") and not col.endswith(" Exp"))]

# Create a new DataFrame with the filtered columns
filtered_arranged_table_02 = arranged_table_reordered[filtered_columns]

# Save the filtered_arranged_table_02 DataFrame to a CSV file
filtered_arranged_table_02.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_02.csv", index=False)

filtered_arranged_table_02

,DepMap_ID,EIF2AK3 (9451) Exp,MYC (4609) Exp,NQO1 (1728) Exp,SF3B1 (23451) Exp,SQSTM1 (8878) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,4.766595,4.820690,7.322018,6.736875,7.886062,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,3.411426,8.787446,2.448901,7.089265,6.109361,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,3.925050,9.105620,3.713696,7.641474,5.591261,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,2.990955,7.170125,7.876578,6.205940,7.836808,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,4.701549,6.685800,7.612574,7.477596,7.430954,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,4.555816,5.855990,6.590961,6.841722,6.361593,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.392317,4.324811,6.670302,6.447744,7.946029,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.286881,4.420213,4.854993,6.480911,7.332887,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.543496,4.729009,9.859938,6.532005,9.047369,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.709291,5.609991,8.146238,6.633141,8.407353,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# Check if there are any missing values

import pandas as pd

# Read the CSV file
filtered_arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")

if filtered_arranged_table.isna().values.any():
    print("The DataFrame has missing values.")
else:
    print("The DataFrame does not have any missing values.")

The DataFrame does not have any missing values.

In [ ]:
# Check if there are any missing values

import pandas as pd

# Read the CSV file
filtered_arranged_table_02 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_02.csv")

if filtered_arranged_table_02.isna().values.any():
    print("The DataFrame has missing values.")
else:
    print("The DataFrame does not have any missing values.")

The DataFrame does not have any missing values.

In [ ]:
# Check if there are any missing values

import pandas as pd

# Read the CSV file
filtered_arranged_table_modified = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified.csv")

if filtered_arranged_table_modified.isna().values.any():
    print("The DataFrame has missing values.")
else:
    print("The DataFrame does not have any missing values.")

The DataFrame does not have any missing values.

In [ ]:
# Find the column names exactly matching the specified strings
target_columns = filtered_arranged_table.columns[filtered_arranged_table.columns.str.match('EIF2AK3 |SF3B1 |NQO1 |SQSTM1 |MYC |HSP70 ')]

target_columns

Index(['EIF2AK3 (9451) Exp', 'MYC (4609) Exp', 'NQO1 (1728) Exp',
       'SF3B1 (23451) Exp', 'SQSTM1 (8878) Exp', 'EIF2AK3 (9451) Dep',
       'MYC (4609) Dep', 'NQO1 (1728) Dep', 'SF3B1 (23451) Dep',
       'SQSTM1 (8878) Dep'],
      dtype='object')

In [ ]:
column_index = filtered_arranged_table.columns.get_loc(filtered_arranged_table.columns[filtered_arranged_table.columns.str.contains("EIF2AK3")][0])
print(column_index)

4481

In [ ]:
column_indices = [i for i, col in enumerate(filtered_arranged_table.columns) if "EIF2AK3" in col]
print(column_indices)

[4481, 17284]

In [ ]:
import pandas as pd

# Read the CSV file and assign it to filtered_arranged_table
filtered_arranged_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")

# Subset of first 10 rows and first 10 columns
subset = filtered_arranged_table.iloc[:11, :11]

# Columns '17284' and '17285'
extra_columns = filtered_arranged_table.iloc[:11, [17284, 17285]]

# Concatenate the subsets horizontally into ML_test_table
ML_test_table = pd.concat([subset, extra_columns], axis=1)

# Save the ML_test_table DataFrame to a CSV file
ML_test_table.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/ML_test_table.csv", index=False)

ML_test_table

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,AADAC (13) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep
0,ACH-000001,3.116032,0.056584,0.226509,0.111031,0.000000,1.035624,0.176323,5.700440,4.144046,0.790772,0.018546,0.807414
1,ACH-000004,4.178715,0.000000,0.214125,0.344828,0.070389,0.097611,0.000000,6.336819,3.231125,0.000000,0.044907,0.999985
2,ACH-000005,4.003602,0.014355,0.137504,0.014355,0.000000,0.028569,0.000000,6.337176,3.781360,0.000000,0.009301,1.000000
3,ACH-000007,0.137504,1.405992,0.201634,0.000000,0.000000,0.014355,0.000000,5.431289,4.300856,3.547203,0.058868,0.999620
4,ACH-000009,1.464668,3.586164,0.250962,0.000000,0.042644,4.525443,0.000000,5.674122,4.510962,1.985500,0.040590,0.979828
5,ACH-000011,1.035624,0.084064,0.042644,0.014355,0.000000,3.531069,0.286881,6.093814,3.758090,0.042644,0.037510,0.995092
6,ACH-000012,2.341986,0.028569,0.070389,0.014355,0.000000,2.226509,0.000000,4.799605,5.122673,0.070389,0.083734,0.999335
7,ACH-000013,2.662205,0.028569,0.084064,0.150560,0.000000,1.298658,0.298658,5.840211,4.494416,0.454176,0.031813,0.950517
8,ACH-000014,6.058749,0.042644,6.260402,0.238787,0.042644,1.226509,0.070389,5.801159,5.118941,0.028569,0.070440,0.953548
9,ACH-000015,4.808385,0.214125,3.297191,0.000000,0.000000,1.280956,0.238787,6.420718,4.139961,0.650765,0.012443,1.000000
10,ACH-000017,3.378512,0.014355,0.163499,3.260026,0.000000,0.150560,0.014355,5.372952,4.817112,0.163499,0.046988,0.998983